# Generated by Django 4.2.3 on 2023-09-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='сustomer',
            new_name='customer',
        ),
    ]
